### ISSUE TITLE
Communication once the game is started

### ISSUE THREAD

**Issue by kristapus** [danderle/WPF_Battleships#1]
Hi, could you confirm that events such as ShotFired or ShotFiredConfirmation are working correctly? The turn of the player never changes for me for some reason. Thank you for your response in advance!

**Comment by danderle** [comment]
I am guessing you are trying to use the SignalR server? I will try to adress this issue hopefully this week.

**Comment by kristapus** [comment]
Sorry, I got a bit confused here :D So, the SignalRServer and BattleshipServer are completely independent implementations? What is the purpose of each?

**Comment by danderle** [comment]
Yes they are independant. One is a tcp server and the other signalR. This repo is part of a tutorial series i am doing on youtube. This is to show that there are different solutions to problem.

**Comment by kristapus** [comment]
Oh, okay. Do you mind sharing that youtube tutorial with me? It would be really helpful

**Comment by danderle** [comment]
[Danderle](https://www.youtube.com/@TheDanderle)

**Comment by kristapus** [comment]
Thank you! So the SignalR implementation is still in progress?

**Comment by danderle** [comment]
Yes. Maximum 2 more videos. But TCP is done and works. So you could just remove the SignalR parts und uncomment everything that has to todo with tcp. Or watch the videos for the complete guide.

**Comment by kristapus** [comment]
Thank you very much!

**Comment by danderle** [comment]
Fixed with last commit
